# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: sudo apt-get install -y libncurses5 libncurses5-dev m4 bison gawk flex libstdc++6-4.7-dev g++-4.7 g++\
 gengetopt git gitk zlib1g-dev autoconf autopoint libtool-bin shtool autogen\
 mtd-utils intltool sharutils docbook-xsl-* libstdc++5 texinfo dos2unix xsltproc\
 u-boot-tools device-tree-compiler qemu gperf liblzo2-dev uuid-dev build-essential\
 lzma-dev liblzma-dev lzma binutils-dev patch cmake intltool libglib2.0-dev\
 gtk-doc-tools
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
